services:
  github2gitea-mirror:
    container_name: github2gitea-mirror

    # build: .
    image: ghcr.io/iamasink/github2gitea-mirror:latest

    environment:
      - ACCESS_TOKEN=xyz
      - GITEA_URL=gitea:3000
      - GITHUB_TOKEN=ghp_abc
    command:
      [
        "bash",
        "-c",
        "env && sleep 60 && ./github2gitea-mirror.sh --mode user --user YOURUSERNAME --visibility public",
      ]
    depends_on:
      - gitea
